bucket_no_upscale = true
bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_extension = ".txt"
dynamo_backend = "no"
enable_bucket = true
epoch = 1
flip_aug = true
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_scale = 1
huber_schedule = "snr"
keep_tokens = 2
learning_rate = 0.0001
loss_type = "l2"
lr_scheduler = "cosine_with_restarts"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 150
max_train_epochs = 12
max_train_steps = 1520
mem_eff_attn = true
min_bucket_reso = 768
mixed_precision = "fp16"
multires_noise_discount = 0.2
multires_noise_iterations = 6
network_alpha = 64
network_args = [ "rank_dropout=0.0", "module_dropout=0.0",]
network_dim = 128
network_dropout = 0.0
network_module = "networks.lora"
network_train_unet_only = false
no_half_vae = true
noise_offset_type = "Multires"
optimizer_args = []
optimizer_type = "AdamW8bit"
output_dir = "C:/Users/chuck/kohya_ss/outputs"
output_name = "DUO_AMBER_CLIN"
pretrained_model_name_or_path = "C:/Users/chuck/ComfyUI/models/checkpoints/illustriousMixedCGI_v20.safetensors"
prior_loss_weight = 1
resolution = "1024,1024"
resume = ""
sample_every_n_steps = 100
sample_prompts = "C:/Users/chuck/kohya_ss/outputs\\sample/prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
save_state = true
save_state_on_train_end = true
scale_weight_norms = 1
shuffle_caption = true
train_batch_size = 1
train_data_dir = "C:/code/comfy_sdk/DUO"
text_encoder_lr = 0.00005
unet_lr = 0.0001
wandb_run_name = "DUO_AMBER_CLIN"
xformers = true
